export const CONSTANTS = {
  THEMES: {
    LIGHT: "LIGHT",
    DARK: "DARK",
  },
  CHAT_ACTIONS: {
    DATA_RESPONSE_ERROR: "DATA_RESPONSE_ERROR",
    DATA_RESPONSE_SUCCES: "DATA_RESPONSE_SUCCES",
    DATA_RESPONSE_IS_FETCHING_TRUE: "DATA_RESPONSE_IS_FETCHING_TRUE",
    DATA_RESPONSE_IS_FETCHING_FALSE: "DATA_RESPONSE_IS_FETCHING_FALSE",
  },
  MENU_ACTIONS: {
    MENU_OPEN: "MENU_OPEN",
    MENU_CLOSE: "MENU_CLOSE",
  },
};
